export const formConfig = [
    {
      id: "name",
      label: "Name",
      name: "name",
      type: "text",
      placeholder: "Enter name",
      isRequired: true,
      controlType: "input",
    },
    {
      id: "projectTypes",
      label: "Project Types",
      name: "projectTypes",
      type: "checkbox",
      placeholder: "Select project types",
      isRequired: true,
      controlType: "checkbox",
      options: ["film", "music", "webseries", "books", "sports"],
    },
    {
      id: "feesType",
      label: "Fees Type",
      name: "feesType",
      type: "select",
      placeholder: "Select fees type",
      isRequired: true,
      controlType: "select",
      options: ["buy", "sell"], // Dropdown options
    },
    {
      id: "percentage_film",
      label: "Percentage for Film",
      name: "percentage_film",
      type: "number",
      placeholder: "Enter percentage for film",
      isRequired: true,
      controlType: "input",
    },
    {
      id: "percentage_music",
      label: "Percentage for Music",
      name: "percentage_music",
      type: "number",
      placeholder: "Enter percentage for music",
      isRequired: false, // Optional field
      controlType: "input",
    },
    {
      id: "percentage_webseries",
      label: "Percentage for Webseries",
      name: "percentage_webseries",
      type: "number",
      placeholder: "Enter percentage for webseries",
      isRequired: false,
      controlType: "input",
    },
    {
      id: "percentage_books",
      label: "Percentage for Books",
      name: "percentage_books",
      type: "number",
      placeholder: "Enter percentage for books",
      isRequired: false,
      controlType: "input",
    },
    {
      id: "percentage_sports",
      label: "Percentage for Sports",
      name: "percentage_sports",
      type: "number",
      placeholder: "Enter percentage for sports",
      isRequired: false,
      controlType: "input",
    },
  ];
  